# Generated by Django 3.1.3 on 2022-04-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220422_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeted',
            new_name='created',
        ),
    ]
