# Generated by Django 4.0.3 on 2022-07-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_order_alter_module_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='desciption',
            new_name='description',
        ),
    ]
